### ISSUE TITLE
Confusion about where ORM docs live

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/orm-docs#14]
It is confusing that the ORM docs are in both this orm-docs repo and the MasoniteFramework/docs. I think the plan is for the documentation to live in this repo since the ORM can be used outside Masonite.

Can this get cleaned up, please?

The main reason I'm mentioning this is because a very important update to capitalize the DB in the config/databases.py file was made here:
https://github.com/MasoniteFramework/docs/commit/37f148f50c3daca752e09220c5d074e957b4ffba
but hasn't been made in this repo and needs to be!

This ended up costing me quite a bit of time as I was trying to upgrade from 2.3 to 3.0 and it would be nice to save some others the pain.

**Comment by josephmancuso** [comment]
The ORM used to live in the Masonite docs but that causes confusion i think as well. So the official place for all things Masonite ORM is in the https://orm.masoniteproject.com website.

I have noticed there is a lowercase db in the docs. I removed the confusion in the masonite docs and fixed the typo in the orm docs. 

Thanks for the report. Let me know if theres anything else confusing. The package is only as good as its documentation.
