### ISSUE TITLE
Document eager loading __with__

### ISSUE THREAD

**Issue by tpow** [MasoniteFramework/orm-docs#26]
It would be helpful to document the `__with__` attribute for eager loading. I was looking for it in the documentation section that [discusses eager loading](https://orm.masoniteproject.com/models).

This feature was added in https://github.com/MasoniteFramework/orm/issues/142 but is undocumented.

**Comment by josephmancuso** [comment]
Documented here https://orm.masoniteproject.com/models#eager-loading
